#!/usr/bin/env Rscript
root <- normalizePath(if(length(commandArgs(trailingOnly=TRUE))) commandArgs(trailingOnly=TRUE)[1] else ".")
source(file.path(root,"R/economic_model.R"))
parameters_path <- file.path(root,"economic_model/parameters/economic_parameters.csv")
forecast_path <- file.path(root,"outputs/notebook_ml/future_forecasts.csv")
ears_path <- file.path(root,"data/input/ears_net_ecoli_blood.csv")
demographics_path <- file.path(root,"data/input/demographics.csv")
coverage_path <- file.path(root,"data/input/ecdc_earsnet_coverage_2023.csv")
population_path <- file.path(root,"data/input/eurostat_population_projection_2026.csv")
parameters <- read_parameters(parameters_path)
config <- read_model_config(file.path(root,"economic_model/model_config.csv"))
cohort <- prepare_economic_cohort(forecast_path,ears_path,demographics_path,coverage_path,population_path,config,parameters)
country <- deterministic_cea(cohort,parameters)
psa <- run_psa(cohort,parameters)
summary <- summarise_psa(psa)
correlation <- run_correlation_sensitivity(cohort,parameters)
one_way <- one_way_sensitivity(cohort,parameters)
output <- file.path(root,"outputs/economic_r"); figures <- file.path(output,"figures")
dir.create(output,recursive=TRUE,showWarnings=FALSE)
write.csv(cohort,file.path(output,"economic_cohort.csv"),row.names=FALSE)
write.csv(country,file.path(output,"deterministic_country_results.csv"),row.names=FALSE)
write.csv(psa,file.path(output,"psa_results.csv"),row.names=FALSE)
write.csv(summary,file.path(output,"psa_summary.csv"),row.names=FALSE)
write.csv(correlation,file.path(output,"correlation_sensitivity.csv"),row.names=FALSE)
write.csv(one_way,file.path(output,"one_way_sensitivity.csv"),row.names=FALSE)
create_cea_figures(country,psa,correlation,one_way,figures,parameters)
paths <- c(parameters_path,forecast_path,ears_path,coverage_path,population_path)
hashes <- tools::md5sum(paths)
metadata <- data.frame(Field=c("authoritative","engine","r_version","random_seed","psa_simulations",
  "cross_country_forecast_correlation","generated_at_utc",paste0("md5_",basename(paths))),
  Value=c("true","R_authoritative",R.version.string,parameter_value(parameters,"random_seed"),
  parameter_value(parameters,"psa_simulations"),parameter_value(parameters,"cross_country_forecast_correlation"),
  format(Sys.time(),tz="UTC",usetz=TRUE),unname(hashes)))
write.csv(metadata,file.path(output,"analysis_metadata.csv"),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(output,"R_SESSIONINFO.txt"))
cat("Authoritative R CEA complete.\n")
